### ISSUE TITLE
on_error hook support

### ISSUE THREAD

**Issue by tnorris** [pdrakeweb/sof#56]
Hi,

I think it would be useful if sof had error hook support, that way a plugin could have a remediation step built in. User hits "y" to run, and hopefully the stuff is resolved.

**Comment by pdrakeweb** [comment]
Interesting idea.  I think the tough part would be knowing in what order to attempt remediations when more than one failure occurs on a given server.  We could prompt with a set of possible remediations for selection rather than a simple y/n.
