### ISSUE TITLE
Flag to disable color

### ISSUE THREAD

**Issue by tnorris** [pdrakeweb/sof#61]
I want to pipe `sof` output into JIRA, but I keep getting ansi escape codes from colors.

Right now my workaround is pipe the output to `| perl -pe 's/\e\[?.*?[\@-~]//g'` before piping it to `comment`, but it would be cool if I could set an environment variable, or if `sof` checked to see if `STDOUT` was a TTY before printing out color.

**Comment by blkperl** [comment]
@tnorris I'm wondering if the better option is to file a feature request here: https://github.com/fazibear/colorize

**Comment by tnorris** [comment]
@blkperl it is a feature of colorize, but sof doesn't use it: https://github.com/fazibear/colorize/blob/1513bb3119fa87cdc95d4d18c696754e40fe7ca5/lib/colorize/class_methods.rb#L7
